### ISSUE TITLE
Have I Been Pwned Errors

### ISSUE THREAD

**Issue by Th4ntis** [thehack3r4chan/OpenAnalysis#1]
When I enter an emailed address for Have I Been Pwned:

> Traceback (most recent call last):
>   File "OpenAnalysis.py", line 909, in <module>
>     main()
>   File "OpenAnalysis.py", line 896, in main
>     hibpWorker(argList[0])
>   File "OpenAnalysis.py", line 792, in hibpWorker
>     parsable = json.loads(emailBreachRequest)
>   File "/usr/lib/python3.6/json/__init__.py", line 344, in loads
>     s, 0)
> json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

**Comment by thehack3r4chan** [comment]
This is due to the API Key associated with the HaveIBeenPwnd account no longer having access API. I just now realized that Troy made that change back in June. https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/
